# Generated by Django 2.2.3 on 2019-07-10 10:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('group_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(max_length=128)),
                ('public_ip', models.GenericIPAddressField(null=True)),
                ('protocol', models.CharField(max_length=10)),
                ('port', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.CharField(max_length=128, null=True)),
                ('model', models.CharField(max_length=128, null=True)),
                ('cpu_cores', models.CharField(max_length=128, null=True)),
                ('disk_info', models.CharField(max_length=1024, null=True)),
                ('os', models.CharField(max_length=1024, null=True)),
                ('sn', models.CharField(max_length=128, null=True)),
                ('number', models.CharField(max_length=32, null=True)),
                ('remarks', models.CharField(max_length=1024, null=True)),
                ('cpu_model', models.CharField(max_length=128, null=True)),
                ('memory', models.CharField(max_length=128, null=True)),
                ('disk_total', models.CharField(max_length=1024, null=True)),
                ('platform', models.CharField(max_length=1024, null=True)),
                ('os_version', models.CharField(max_length=128, null=True)),
                ('os_arch', models.CharField(max_length=128, null=True)),
                ('hostname_raw', models.CharField(max_length=128, null=True)),
                ('date_crated', models.DateTimeField(default=django.utils.timezone.now)),
                ('assets_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.AssetGroup')),
                ('assets_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Administrator')),
            ],
        ),
    ]
